export const MESSAGE = {
  GET_DASHBOARD_SUCCESS: 'Successfully get dashboard',
  LOGOUT_SUCCESS: 'Successfully logged out',
  GET_USER_SUCCESS: 'Successfully get user',
  CHANGE_PASSWORD_SUCCESS: 'Successfully changed password',
  CHANGE_PROFILE_SUCCESS: 'Successfully changed profile',
  EMAIL_NOT_VERIFIED: 'Please verify your email first',
  RESEND_EMAIL_SUCCESS: 'Email verification sent',
  REGISTER_SUCCESS: 'Successfully registered',
  EMAIL_NOT_FOUND: 'Email not found',
  EMAIL_VERIFIED: 'Email Successfully Verified',
  EMAIL_EXISTED: 'Email already exists',
  AUTH_INVALID: 'The credentials are incorrect',
  LOGIN_FAILED: 'Email or password is incorrect',
  LOGIN_SUCCESS: 'Successfully logged in',
  GET_PROFILE_SUCCESS: 'Successfully get profile',
  USER_MANAGE_SUCCESS: 'Save completed',
};
